### ISSUE TITLE
[Question] Usage of package.json

### ISSUE THREAD

**Issue by joshhornby** [richardkall/react-starter#2]
What is the logic behind using `package.json` which each component?  What advantages does this give?

Thanks

**Comment by richardkall** [comment]
I only use it for specifying an entry point to the component using the `main` field in `package.json`. By doing this I can import the component directly from its folder. So instead of `import Header from 'components/Header/Header'` I can use `import Header from 'components/Header'`.

Another solution would be to rename `Header.js` to `index.js` but then it's hard to see which component is which in my editor tabs.

**Comment by joshhornby** [comment]
Nice, I like that idea. Thanks for the response.
